version: "3.7"

services:
  jenkins:
    environment:
      DOCKER_HOST: "tcp://jenkins-docker-proxy:2375"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.jenkins-redirect-web-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.ops.katiecordescodes.com`)"
      - "traefik.http.routers.jenkins.entryPoints=web"
      - "traefik.http.routers.jenkins.middlewares=jenkins-redirect-web-secure"
      - "traefik.http.routers.jenkinssecure.rule=Host(`jenkins.ops.katiecordescodes.com`)"
      - "traefik.http.routers.jenkinssecure.entryPoints=websecure"
      - "traefik.http.routers.jenkinssecure.tls=true"
      - "traefik.http.routers.jenkinssecure.tls.certresolver=myresolver"
      - "traefik.http.services.jenkinssecure.loadBalancer.server.port=8080"