version: "3.7"

services:
  jenkins:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: jenkins
    restart: always
    environment:
      JAVA_ARGS: "-Xmx512m"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - traefik

volumes:
  jenkins-data:

networks:
  traefik:
    external: true