version: "3.7"

services:
  jenkins:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: jenkins
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      DOCKER_HOST: "tcp://jenkins-docker-proxy:2375"
    networks:
      - traefik
      - jenkins-docker-proxy

networks:
  traefik:
    external: true
  jenkins-docker-proxy:
    external: true

volumes:
  jenkins-data: