version: "3.7"

services:
  jenkins:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.localhost`)"
      - "traefik.http.routers.jenkins.entryPoints=web"
      - "traefik.http.services.jenkins.loadBalancer.server.port=8080"
      - "traefik.docker.network=traefik"